pipeline {
    agent none

    stages {
        stage('Install Dependencies') {
            when {
                changeset "**/vote/**"
            }
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '--user root'
                }
            }
            steps {
                echo 'Installing dependencies for vote app...'
                dir('vote') {
                    sh "pip install -r requirements.txt"
                    sh "pip list" // Verificar que las dependencias estén instaladas
                }
            }
        }

        stage('Run Tests') {
            when {
                changeset "**/vote/**"
            }
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '--user root'
                }
            }
            steps {
                echo 'Running unit tests on vote app...'
                dir('vote') {
		    sh 'pip install nose2'
                    sh 'python -m nose2 -v'
                }
            }
        }

        stage('Package with Docker') {
            agent any
            when {
                changeset "**/vote/**"
                branch 'master'
            }
            steps {
                echo 'Packaging vote app with Docker...'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                        def voteImage = docker.build("pabloflores2615/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push()
                        voteImage.push("${env.BRANCH_NAME}")
                        voteImage.push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline for vote is complete'
        }
    }
}
