pipeline {
    agent {
        docker {
            image 'maven:3.9.8-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running unit tests on worker app'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            steps {
                echo 'Packaging worker app into a JAR file'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
        stage('Docker Package') {
            agent any
            steps {
                echo 'Packaging worker app with Docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                        def workerImage = docker.build("pabloflores2615/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("latest")
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'The job is complete'
        }
    }
}
